language = "C"

include_guard = "__bbs__plus__included__"

after_includes = """
typedef enum SignatureProofStatus {
    Success = 200,
    BadSignature = 400,
    BadHiddenMessage = 401,
    BadRevealedMessage = 402
} SignatureProofStatus;
"""

[defines]
"target_os = android" = "DEFINE_ANDROID"
"feature = java" = "DEFINE_JAVA"

[parse]
parse_deps = true
include = ["ffi-support"]

[parse.expand]
crates = ["ffi-bbs-signatures"]
