/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bbs.signatures;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        try {
            KeyPair keyPair = Bbs.generateBls12381G1Key(null);
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }
}
