/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bbs */

#ifndef _Included_Bbs
#define _Included_Bbs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Bbs
 * Method:    bls_generate_g1_key
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_Bbs_bls_1generate_1g1_1key
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Bbs
 * Method:    bls_generate_g2_key
 * Signature: ([B[B[B)I
 */
JNIEXPORT jint JNICALL Java_Bbs_bls_1generate_1g2_1key
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Bbs
 * Method:    bls_generate_blinded_g1_key
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_Bbs_bls_1generate_1blinded_1g1_1key
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Bbs
 * Method:    bls_generate_blinded_g2_key
 * Signature: ([B[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_Bbs_bls_1generate_1blinded_1g2_1key
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     Bbs
 * Method:    bls_secret_key_to_bbs_key
 * Signature: ([BILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_Bbs_bls_1secret_1key_1to_1bbs_1key
  (JNIEnv *, jclass, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
