/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bbs.signatures;

public class Library {
    static {
        System.loadLibrary("bbs");
    }

    public static native int bls_generate_g1_key(byte[] seed, byte[] public_key, byte[] secret_key);
}
