jobs:
- job: Package_Nuget

  pool:
    vmImage: 'macos-latest'
  variables:
    solution: '**/*.sln'
    buildConfiguration: 'Release'

  steps:

  - task: DownloadPipelineArtifact@2
    inputs:
      buildType: 'current'
      itemPattern: |
        **/*.a
        **/*.dylib
        **/*.so
        **/*.dll
      targetPath: 'dotnet/libs'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(solution)'
      feedsToUse: 'select'

  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '/t:build,pack /p:PackageOutputPath=$(Agent.BuildDirectory)/dotnet/nuget'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Agent.BuildDirectory)/dotnet/nuget/'
      ArtifactName: 'nuget'
      publishLocation: 'Container'