jobs:
- job: Package_Nuget

  pool:
    vmImage: 'macos-latest'
  steps:
  - task: PowerShell@2
    inputs:
      filePath: 'devops/Build.ps1'
      arguments: '-Platform ${{ parameters.platform }} -OutLocation $(Build.ArtifactStagingDirectory) ${{ parameters.additionalArguments }}'
      pwsh: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${{ parameters.platform }}'
      publishLocation: 'Container'