name: ci-java

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test:
    name: Build & Test Java Wrapper
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: macos-latest
    strategy:
      matrix:
        jdk-version: [11, 17, 21]
        jvm-build-version: [21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.jdk-version }}
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: |
            ${{ matrix.jdk-version }}
      - name: Set up JVM for building ${{ matrix.jvm-build-version }}
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: |
            ${{ matrix.jdk-version }}
      - name: Show env
        run: env | grep -i java
      - name: Build with Gradle
        working-directory: ./wrappers/java
        run: ./gradlew build -Dorg.gradle.java.home=$JAVA_HOME_${{ matrix.jdk-version }}_arm64 -PtargetVersion=${{ matrix.jdk-version }} --stacktrace --debug
