name: ci-java

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}-java

jobs:
  build_test:
    name: Build & Test Java Wrapper
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: macos-latest
    strategy:
      matrix:
        java-version: [11, 17, 21]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "adopt"
      - name: Build with Gradle
        working-directory: ./wrappers/java
        run: ./gradlew build
