name: ci-obj-c

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build_test:
    name: Build & Test Objective-C Wrapper
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build binary for IOS
        run: yarn build:ios

      - name: Update binary for wrapper
        run: yarn wrapper:obj-c:update-binary

      - name: List Installed Xcode Versions
        run: |
          echo "Listing installed Xcode versions:"
          ls -1 /Applications | grep Xcode

      - name: Verify Xcode Path
        run: |
          echo "Checking Xcode Developer Directory..."
          ls -ld /Applications/Xcode_14.2.app/Contents/Developer || echo "Path not found or inaccessible"

      - name: Build and test wrapper
        run: yarn wrapper:obj-c:build
        env:
          DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
